runtime: nodejs18
service: yanuar

env_variables:
  NODE_ENV: production
  PORT: 8080

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10